### ISSUE TITLE
A way to load Spacemacs dashboard only without additional settings .

### ISSUE THREAD

**Issue by M1ndo** [chenyanming/spacemacs_module_for_doom#11]
Thank you by the way for this awesome module for doom emacs , tho one minor issue i've came across is loading and evaluating unecessary packages and settings that came with spacemacs module.
i tried to load only spacemacs dashboard however i couldn't figure out how to do it properly , is there any way to do it ?

**Comment by chenyanming** [comment]
There is no easy way to do this, you need to follow the https://github.com/chenyanming/spacemacs_module_for_doom#load-this-module-directly section, and modify the `config.el` and `packages.el` by yourself.

You can uncomment the configs you don't need in `config.el` and `packages.el`.
