### ISSUE TITLE
Clojure transient state

### ISSUE THREAD

**Issue by lccambiaghi** [chenyanming/spacemacs_module_for_doom#6]
Hi, my biggest wish from the Spacemacs distribution is the clojure layer, in particular its transient state binded to `SPC k`. Would it be difficult for you to add it? 
It is amazing that you went through the effort of integrating spacemacs core!

**Comment by chenyanming** [comment]
Sorry, I am not very familiar with clojure. But you can port any layers if you want by yourself. 

Steps:

1. Copy the Clojure layer folder into this project's `layer` folder
2. Load three files: `packages.el`, `config.el` and `funcs.el`. 
3. Call the init functions in `packages.el` in this package's `+spacemacs.el`

It is easy, but you may need some tests. If some conflicts occur, just comment out the conflicts codes in the corresponding files.

For example, javascript layer:
```
;; javascript layer
(load! (concat spacemacs-path "spacemacs/layer/javascript/packages.el"))
(load! (concat spacemacs-path "spacemacs/layer/javascript/config.el"))
(load! (concat spacemacs-path "spacemacs/layer/javascript/funcs.el"))
(javascript/init-js2-mode)
;; you can only choose either nodejs or skewer
(setq javascript-repl 'nodejs)          ; choose nodejs
(javascript/init-nodejs-repl)

```
