### ISSUE TITLE
Using org-want-todo-bindings variable

### ISSUE THREAD

**Issue by bi1yeu** [chenyanming/spacemacs_module_for_doom#8]
Hi, is there a way to support the `org-want-todo-bindings` variable? From the [documentation](https://github.com/chenyanming/spacemacs_module_for_doom/blob/master/layer/org/README.org):

> If the layer variable `org-want-todo-bindings` is true, the following bindings are also available. [... `t`, `T`, `M-t`]

I've tried setting this variable in `~/.doom.d/config.el` (see below), but this does not appear to work. E.g., if I type `t` from normal mode in an org-mode buffer when the cursor is over a heading, I'd expect the heading's TODO state to cycle, but instead the messages area displays `1>` and nothing happens.

```
(defvar org-want-todo-bindings t)
(load! "~/.doom.d/modules/spacemacs/+spacemacs")
```

Any help is appreciated, thanks!

**Comment by chenyanming** [comment]
Please check now! It is enabled by default.
